project_name: certkeeper

before:
  hooks:
    - go mod tidy

builds:
  - id: certk-server
    main: ./cmd/server
    binary: certk-server
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/siidoo/certkeeper/internal/version.Version={{.Version}}
      - -X github.com/siidoo/certkeeper/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/siidoo/certkeeper/internal/version.BuildDate={{.Date}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - darwin_amd64
      - darwin_arm64
  - id: certk-client
    main: ./cmd/client
    binary: certk-client
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/siidoo/certkeeper/internal/version.Version={{.Version}}
      - -X github.com/siidoo/certkeeper/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/siidoo/certkeeper/internal/version.BuildDate={{.Date}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - darwin_amd64
      - darwin_arm64
  - id: certk-server-cli
    main: ./cmd/server-cli
    binary: certk-server-cli
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    ldflags:
      - -s -w
      - -X github.com/siidoo/certkeeper/internal/version.Version={{.Version}}
      - -X github.com/siidoo/certkeeper/internal/version.GitCommit={{.ShortCommit}}
      - -X github.com/siidoo/certkeeper/internal/version.BuildDate={{.Date}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm
      - darwin_amd64
      - darwin_arm64

archives:
  - ids: [certk-server]
    name_template: certk-server_{{ .Os }}_{{ .Arch }}
  - ids: [certk-client]
    name_template: certk-client_{{ .Os }}_{{ .Arch }}
  - ids: [certk-server-cli]
    name_template: certk-server-cli_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^chore:'
      - '^test:'

release:
  github:
    owner: qozi
    name: cert-keeper
  draft: false
  prerelease: auto
